chore: jumper clean up tracking tools
jumperexchange/jumper-exchange pull request #1027
Opened 2024-06-07 14:36 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-7747

2024-06-10 10:12 UTC, tcheee commented on src/components/Menus/WalletMenu/WalletCard.tsx
> +        label: 'pageload-discord',
typo on the label no?

2024-06-10 10:12 UTC, tcheee commented on src/components/PoweredBy/PoweredBy.tsx
> +      label: 'pageload-discord',
typo as well?

2024-06-10 10:12 UTC, tcheee commented on src/components/WelcomeScreen/WelcomeScreen.tsx
> +      label: 'pageload-discord',
same

2024-06-10 10:12 UTC, tcheee commented on src/types/userTracking.ts
> -  account?: Account;
How do we track chainSwitch now?

2024-06-10 10:12 UTC, tcheee commented on tests/e2e.spec.ts
> +    await page.locator('.profile-page').isVisible({ timeout: 15000 });
please merge last develop to avoid issue here

2024-06-13 15:58 UTC, dennyscode commented on src/components/Menus/WalletMenu/WalletCard.tsx
> +        label: 'pageload-discord',
Yesss! Good find, thanks!

2024-06-13 15:59 UTC, dennyscode commented on src/components/PoweredBy/PoweredBy.tsx
> +      label: 'pageload-discord',
Yes, right. Good find!!!

2024-06-13 19:40 UTC, dennyscode commented on src/types/userTracking.ts
> -  account?: Account;
I have added it now to the Widget.tsx.

2024-07-26 08:15 UTC, oktapodia requested changes
Mainly a question

2024-07-26 08:15 UTC, oktapodia commented on src/components/Widgets/Widget.tsx
> -    theme.breakpoints,
deleting those might break the theme switching

2024-07-26 10:20 UTC, admsk2 approved these changes

2024-08-05 14:50 UTC, oktapodia approved these changes
LGTM

2024-08-05 14:59 UTC, merged