Update readme
jumperexchange/jumper-exchange pull request #1245
Opened 2024-08-15 09:36 UTC by oktapodia

2024-08-15 09:57 UTC, chybisov requested changes
Build fails for some reason 👀

2024-08-15 09:57 UTC, chybisov commented on src/components/Superfest/SuperfestPage/SuperfestMisisonPage.tsx
>    const points = quest?.attributes?.Points;
I guess we can remove `?` from here as we now have a check for quest above.

2024-08-15 12:14 UTC, chybisov approved these changes

2024-08-20 08:53 UTC, dennyscode approved these changes

2024-09-09 10:55 UTC, merged