chore: sending available routes only on changed inputs
jumperexchange/jumper-exchange pull request #1313
Opened 2024-09-17 09:43 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-9812

2024-09-17 10:35 UTC, oktapodia requested changes
Couple of comments

2024-09-17 10:36 UTC, dennyscode commented on src/components/Widgets/WidgetEvents.tsx
> +  numRoutes?: number;
100% I was having a hard time finding a proper name! Thank you

2024-09-17 13:09 UTC, dennyscode commented on src/components/Widgets/WidgetEvents.tsx
> +        previousRoutesRef.current.numRoutes !== availableRoutes.length ||
Nice, trying that!

2024-09-17 13:10 UTC, dennyscode commented on src/components/Widgets/WidgetEvents.tsx
> +  const previousRoutesRef = useRef<PreviousRoutesRefProps>({
Please, check! I have actually provided values of undefined to prevent an "undefined" error later in the process. Wdyt?

2024-09-19 07:52 UTC, oktapodia commented on src/components/Widgets/WidgetEvents.tsx
> +        previousRoutesRef.current[TrackingEventParameter.AvailableRoutesCount] =
not needed to do this, just do previousRoutesRef.current = newObj as you've just created an object matching this interface..

2024-09-19 07:52 UTC, oktapodia commented on src/components/Widgets/WidgetEvents.tsx
> +      delete prevRefObj?.[TrackingEventParameter.TxHash];
Why is that needed?

2024-09-19 07:53 UTC, oktapodia commented on src/components/Widgets/WidgetEvents.tsx
> +      const prevRefObj = previousRoutesRef.current;
Why is that needed?

2024-09-24 08:18 UTC, oktapodia approved these changes
LGTM

2024-09-24 14:54 UTC, tcheee commented on src/components/Widgets/WidgetEvents.tsx
> +            [TrackingEventParameter.AvailableRoutesCount]:
we are missing information there

2024-09-26 15:03 UTC, merged