feat: add badge for first trait
jumperexchange/jumper-exchange pull request #1431
Opened 2024-10-21 17:18 UTC by tcheee

2024-10-21 17:40 UTC, admsk2 commented on src/components/ProfilePage/QuestCardDetailled/QuestCardDetailled.tsx
> +              </BadgeRelativeBox>
How about:
```
{isTraitsGarded &&
   <BadgeRelativeBox>
     <TraitsBox trait={'perp_oors'} />
   </BadgeRelativeBox>
}
```

2024-10-21 19:27 UTC, tcheee commented on src/components/ProfilePage/QuestCardDetailled/QuestCardDetailled.tsx
> +              </BadgeRelativeBox>
yes

2024-10-22 06:28 UTC, admsk2 approved these changes

2024-10-22 07:04 UTC, dennyscode requested changes
Nice!!! Working fine, but only one thing I noticed - maybe we can adjust the zIndex?

![image](https://github.com/user-attachments/assets/862743c0-ffb1-4358-adaa-1cea35243497)

2024-10-22 08:11 UTC, oktapodia approved these changes
LGTM

2024-10-22 10:47 UTC, dennyscode approved these changes

2024-10-22 10:51 UTC, merged