feat: Remove path params when swapping tabs
jumperexchange/jumper-exchange pull request #1496
Opened 2024-11-07 11:57 UTC by oktapodia

2024-11-13 16:06 UTC, tcheee commented on src/components/Menus/VerticalMenu/useVerticalTabs.tsx
> +    router.push(`/${tab}`);
can you keep everything and just remove the "toToken" from the path  pls @oktapodia

2024-11-14 07:17 UTC, dennyscode approved these changes

2024-11-14 07:25 UTC, dennyscode requested changes
Not sure! Although I like the approach you took, this might be misleading to our users!

Not all chains are supported on the Refuel-Widget: If we keep the SearchParams, it also suggests those ones. I think either removing it, or keeping searchParams elsewhere (zustand temporary or persistent) for each tab would be the cleaner way. Wdyt?

![image](https://github.com/user-attachments/assets/dceb1d12-0c31-4ea3-8120-539c8e780b65)

2024-11-14 09:35 UTC, dennyscode approved these changes

2024-11-14 10:17 UTC, merged