feat: Add redirectUrl to strapi blog article
jumperexchange/jumper-exchange pull request #1527
Opened 2024-11-19 11:13 UTC by oktapodia

2024-11-19 17:55 UTC, tcheee commented
I think as the blog are not live anymore and won't be. We need to have a redirection when arriving on the page like inside a useEffect or equivalent, no?

2024-11-19 17:55 UTC, tcheee requested changes

2024-11-19 17:55 UTC, tcheee commented on src/components/Blog/BlogArticleCard/BlogArticleCard.tsx
> +      href={
won't be enough imho.

2024-11-25 18:11 UTC, tcheee approved these changes

2024-12-12 10:20 UTC, dennyscode approved these changes

2025-01-08 12:22 UTC, merged