feat: Use blockies lib instead of effigy
jumperexchange/jumper-exchange pull request #1528
Opened 2024-11-22 10:09 UTC by oktapodia

2024-11-22 17:05 UTC, tcheee commented
ENS image check seems to be failing
<img width="394" alt="image" src="https://github.com/user-attachments/assets/a13e27cd-75b9-4833-ab10-4481826851b5">

2024-11-22 17:07 UTC, tcheee requested changes

2024-11-22 17:07 UTC, tcheee commented on src/components/Navbar/WalletButton.tsx
> +  const imgLink = useBlockieImg(account?.address);
we need to check ENS image as well

2024-12-02 10:29 UTC, tcheee approved these changes

2024-12-02 10:39 UTC, dennyscode approved these changes

2024-12-02 13:14 UTC, merged