feat: Zapping;
jumperexchange/jumper-exchange pull request #1550
Opened 2024-11-27 15:50 UTC by admsk2

2024-12-11 10:05 UTC, chybisov requested changes

2024-12-11 10:05 UTC, chybisov commented on src/providers/WalletProvider/ZapWalletProvider.tsx
> +  });
Maybe we should set this only on mount?

2024-12-11 10:05 UTC, chybisov commented on src/app/[lng]/custom-widget/layout.tsx
> +    <>
Unnecessary fragments

2024-12-11 10:05 UTC, chybisov commented on src/app/[lng]/custom-widget/layout.tsx
> +import { WalletProviderZap } from 'src/providers/WalletProvider/ZapWalletProvider';
The name of the component and file could be more consistent 😅

2025-01-13 14:21 UTC, dennyscode requested changes
Few small things I noticed which I also tackled for the mui v6 upgrade

2025-01-13 14:21 UTC, dennyscode commented on src/components/ZapWidget/Deposit/Stat/DigitOnlyCard.tsx
> +        fontWeight={700}
to align on the MUI v6 updates, let´s put this into sx props to make sure

2025-01-13 14:21 UTC, dennyscode commented on src/components/Zap/BackButton/BackButton.tsx
> +          marginLeft={'8px'}
Let´s add to sx props

2025-01-13 14:21 UTC, dennyscode commented on src/components/ZapWidget/TxConfirmation.tsx
> +        <Typography color={theme.palette.text.primary}>{s}</Typography>
color needs to go into sx props

2025-01-13 14:21 UTC, dennyscode commented on src/components/ZapWidget/Deposit/Stat/DigitTextCard.tsx
> +            color={hasDeposited ? theme.palette.primary.main : undefined}
To make sure, let´s put marginTop, fontWeight and especially color into sx props

2025-01-13 16:42 UTC, oktapodia requested changes
Couple of comments

2025-01-13 16:42 UTC, oktapodia commented on src/app/[lng]/zap/[slug]/page.tsx
> +    const questData = (quest.data as any as Quest)
as any as Quest seems weird there, getQuestBySlug should return the correct type alrady

2025-01-13 16:42 UTC, oktapodia commented on src/app/[lng]/zap/[slug]/page.tsx
> +      .attributes as QuestAttributes;
Same as above

2025-01-13 16:42 UTC, oktapodia commented on src/app/lib/getQuestBy.ts
> +    cache: 'no-store',
is that expected?

2025-01-13 16:42 UTC, oktapodia commented on src/app/ui/learn/LearnArticlePage.tsx
> +          subtitle={article?.attributes?.Subtitle}
Would be better to pass the whole article to the BlogArticle component

2025-01-13 16:42 UTC, oktapodia commented on src/components/Superfest/AvailableMissionsList/AvailableMissionsList.tsx
> +                  title={quest?.attributes?.Title}
Would be better to pass the quest object to QuestCard

2025-01-13 16:42 UTC, oktapodia commented on src/components/Zap/WidgetLikeField/WidgetLikeField.tsx
> +                borderRadius: theme.spacing(2),
A styled component would be better (same for the whole file)

2025-01-13 20:42 UTC, tcheee commented on src/app/[lng]/zap/[slug]/page.tsx
> +    const questData = (quest.data as any as Quest)
should be fixed, change the return of the functions

2025-01-13 20:43 UTC, tcheee commented on src/app/[lng]/zap/[slug]/page.tsx
> +      .attributes as QuestAttributes;
same

2025-01-13 20:49 UTC, tcheee commented on src/app/lib/getQuestBy.ts
> +    cache: 'no-store',
Well, I had issue refreshing data locally

2025-01-13 20:50 UTC, tcheee commented on src/app/ui/learn/LearnArticlePage.tsx
> +          subtitle={article?.attributes?.Subtitle}
Not related to this PR but kinda agree, i'll create a ticket to clean this up.

2025-01-13 20:52 UTC, tcheee commented on src/components/Superfest/AvailableMissionsList/AvailableMissionsList.tsx
> +                  title={quest?.attributes?.Title}
https://lifi.atlassian.net/browse/LF-11745

2025-01-13 20:53 UTC, tcheee commented on src/hooks/useIonicData.ts
> +        return { data: null };
not used anymore. Removed.

2025-01-13 20:58 UTC, tcheee commented on src/components/ZapWidget/TxConfirmation.tsx
> +      sx={{
agree

2025-01-20 15:58 UTC, oktapodia approved these changes
LGTM

2025-01-20 15:59 UTC, merged