WIP royco
jumperexchange/jumper-exchange pull request #1577
Opened 2024-12-09 15:13 UTC by oktapodia

2025-01-09 10:11 UTC, admsk2 approved these changes

2025-01-09 13:28 UTC, dennyscode commented
![image](https://github.com/user-attachments/assets/e0108598-2f69-4138-8742-21b1f39c3d47)

> After the launch of Berachain, withdrawal of funds and claiming of rewards will be done on website. You'll be able to access it here.

Can we add some info about "on what" website? Like "on the protocols` website".

2025-01-09 14:00 UTC, dennyscode commented
Not sure if we still wanted to make the filterbox responsive in a way that it shows if filters have been applied. I played around with it and it could be added like so:

![image](https://github.com/user-attachments/assets/faf0fd5c-e358-43bc-b8d3-9ea93d571410)

```
  const tokensNumber = Array.isArray(tokens) ? tokens.length : tokens.size;
  const tokensFiltered = tokensNumber - tokenFilter.length;
....

        <Typography variant="bodyMedium">
          {tokensNumber !== tokensFiltered
            ? `${tokensFiltered} Token${tokensFiltered === 1 ? '' : 's'}`
            : 'All Tokens'}
        </Typography>

```

This example only applies to the token-filter, we could re-use such logic to add it for the incentives (protocols) filter.

2025-01-09 14:01 UTC, dennyscode commented
Just to not forget: **tbd**

![image](https://github.com/user-attachments/assets/ce28801d-4651-4ae0-8088-c96e366ef8c0)

2025-01-09 14:09 UTC, dennyscode commented
When clicking "Switch chain", Metamask is not popping up to proceed with the network switch:

--> /berachain/explore/0xe9361c6676c14fe04c72c841d1db72280e0db59b563d5f3e236400078cb4e235

![image](https://github.com/user-attachments/assets/7a2fd891-0e82-49db-a335-ab13c0f051a1)

2025-01-09 14:22 UTC, dennyscode requested changes
There is some old junk I had left which can be removed

2025-01-09 14:22 UTC, dennyscode commented on public/berachain/berachain-lunar-crater-resize.svg
This file can be removed, not used (Was on me!)

2025-01-09 14:22 UTC, dennyscode commented on public/berachain/berachain-lunar-crater.svg
This file can be removed, not used (Was on me!)

2025-01-09 14:22 UTC, dennyscode commented on public/berachain/berachain-moon-surface.svg
This file can be removed, not used (Was on me!)

2025-01-09 14:22 UTC, dennyscode commented on public/berachain/berachain-navbar-logo.png
This file can be removed, not used (Was on me!)

2025-01-09 14:22 UTC, dennyscode commented on public/berachain/berachain-orange-logo.png
This file can be removed, not used (Was on me!)

2025-01-09 14:22 UTC, dennyscode commented on public/berachain/sir-bridgealot-w-glow.png
This file can be removed, not used (Was on me!)

2025-01-10 08:25 UTC, dennyscode approved these changes
Just cleanup stuff we may consider to come back to, if we keep such files for an extended period of time and re-use those.

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetIncentiveTab.tsx
> +                //         whiteSpace: 'nowrap', // Equivalent to `whitespace-nowrap`
Do we need to keep it?

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetIncentiveTab.tsx
> +  console.log('-positions', positions, positionsRecipe, positionsVault);
According to comment: todo - to remove

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WidgetLikeWIP.tsx
> +function WidgetLikeWIP({ contractCalls }: { contractCalls: ContractCall[] }) {
Still need to keep the WIP inside the name?

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WidgetLikeWIP.tsx
> +      console.log('onSuccess triggered');
According to comment: todo to remove comment

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidget.tsx
> +                console.error(error);
According to comment: todo to remove

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetIncentiveTab.tsx
> +  });
According to comment: todo to remove

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetIncentiveTab.tsx
> +        {/*<div className="h-full w-full place-content-center items-start">*/}
Need to keep this comment?

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetIncentiveTab.tsx
> +                        flexDirection: 'column', // Equivalent to `flex-col`
May not be any important for now and does the trick already, but if we keep using this, it smells like a good styled-component

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetIncentiveTab.tsx
> +              // className="w-full"
Need to keep?

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetIncentiveTab.tsx
> +      )} */}
Need to keep?

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetInputTokenTab.tsx
> +  // TODO: to remove
Another todo

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetInputTokenTab.tsx
> +          // marginBottom: theme.spacing(6),
Remove unused

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetInputTokenTab.tsx
> +        {/*<div className="h-full w-full place-content-center items-start">*/}
Remove

2025-01-10 08:25 UTC, dennyscode commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetInputTokenTab.tsx
> +                      },*/
Remove unused

2025-01-10 08:54 UTC, tcheee commented on src/components/Berachain/components/BerachainWidget/WithdrawWidget/WithdrawWidgetIncentiveTab.tsx
> +                        flexDirection: 'column', // Equivalent to `flex-col`
agree, let's keep it unstyled for now to focus on getting it live.

2025-01-10 08:55 UTC, tcheee commented on src/components/Berachain/components/BerachainWidget/WidgetLikeWIP.tsx
> +function WidgetLikeWIP({ contractCalls }: { contractCalls: ContractCall[] }) {
not used, thanks.

2025-01-10 11:00 UTC, merged