chore: adjust bg color on scan page
jumperexchange/jumper-exchange pull request #1578
Opened 2024-12-09 16:30 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-11330

2024-12-12 17:09 UTC, tcheee commented
<img width="779" alt="image" src="https://github.com/user-attachments/assets/ed23c8a6-5d90-4835-8fbd-e272cffc9d41" />
Issue on the menu if the user is coming from a dark theme

2024-12-12 17:09 UTC, tcheee requested changes

2024-12-12 17:09 UTC, tcheee commented on src/components/Menus/MainMenu/useMainMenuContent.tsx
> +  if (configTheme?.hasThemeModeSwitch && !disableThemeSwitch) {
won't be enough as the dark theme does not exist so we have to force the light theme on this page

2024-12-17 20:23 UTC, dennyscode commented
@tcheee I suggest to close this PR. I tried going an extra mile by trying to reduce complexity and avoiding partner-theme for our default themes such as "light" or "dark". But reality is, that our partner-themes are working well and that´s our current solution.

A minor adjustment within the "scan" partner-theme already did the trick and we may go on with that. Here is the current scan page, where we already achieved our goal to have the proper background-color:
![image](https://github.com/user-attachments/assets/c41df2fa-01a3-4630-9878-e2e8a97a4302)

2024-12-18 07:57 UTC, closed without merging